return {
 ["content"]={
  ["files"]={
   ["context"]="bin",
   ["context.lua"]="bin",
   ["luametatex"]="bin",
   ["luatex"]="bin",
   ["mtxrun"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-linux-64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2022-08-04",
 ["root"]="selfautoparent:texmf-linux-64",
 ["time"]="12:28:12",
 ["type"]="files",
 ["uuid"]="bdfa65d2-4a7f-969a-a0a3-dc32bc75e953",
 ["version"]="1.100",
}